services:
  price_observer:
    tty: true
    stdin_open: true
    build: .
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    networks:
      - game-network
    depends_on:
      - price_observer_postgres
    restart: unless-stopped

  price_observer_postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - game-network
    ports:
      - ${POSTGRES_PORT}:5432
    command: postgres -c 'timezone=Europe/Moscow'
    restart: unless-stopped

networks:
  game-network:
    driver: bridge

volumes:
  pgdata:
