"""add cascade delete

Revision ID: ce3e47723f60
Revises: 4c5ccfb307d1
Create Date: 2025-01-29 12:44:03.533584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3e47723f60'
down_revision: Union[str, None] = '4c5ccfb307d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_history_subscription_id_fkey', 'price_history', type_='foreignkey')
    op.create_foreign_key(None, 'price_history', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_foreign_key('price_history_subscription_id_fkey', 'price_history', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
