"""fix name

Revision ID: efc238fad799
Revises: c82a6137803b
Create Date: 2025-01-28 11:27:04.673212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc238fad799'
down_revision: Union[str, None] = 'c82a6137803b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('subscriptions_prodct_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'products', ['product_id'], ['id'])
    op.drop_column('subscriptions', 'prodct_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('prodct_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_prodct_id_fkey', 'subscriptions', 'products', ['prodct_id'], ['id'])
    op.drop_column('subscriptions', 'product_id')
    # ### end Alembic commands ###
